#!/usr/bin/env bash
# deploy/deploy.sh — full production deployment in one command.
#
# What it does (in order):
#   1. Validates prerequisites and the .env.prod file
#   2. Pulls the latest code from Git
#   3. Installs / updates Node dependencies
#   4. Brings up the Docker data layer (PostgreSQL + Redis) and waits for health
#   5. Runs pending Prisma migrations
#   6. Builds all Nx applications for production
#   7. Ensures runtime directories exist
#   8. Deploys nginx config + reloads nginx (idempotent — certs must exist first)
#   9. Starts or hot-reloads all PM2 processes with the refreshed env vars
#
# Usage:
#   bash deploy/deploy.sh              # deploys from 'main'
#   bash deploy/deploy.sh my-branch    # deploys from a specific branch
#
# First-time VPS setup (run ONCE before the first deploy):
#   1. Install deps:  npm install -g pm2 && pm2 startup
#   2. Provision SSL: sudo certbot certonly --standalone \
#                       -d backend.testinglinq.com \
#                       -d admin.testinglinq.com \
#                       -d vendor.testinglinq.com \
#                       -d portal.testinglinq.com
#   3. Then run this script normally — nginx will pick up the certs.

set -euo pipefail

BRANCH="${1:-main}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env.prod"

# ── 0. Prerequisites ──────────────────────────────────────────────────────────
echo "==> Checking prerequisites..."

if [ ! -f "${ENV_FILE}" ]; then
  echo "ERROR: ${ENV_FILE} not found."
  echo "       Copy .env.prod.example → .env.prod and populate all values."
  exit 1
fi

for cmd in git node npx docker pm2; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '${cmd}' is not installed or not in PATH."
    exit 1
  fi
done

# ── Load .env.prod into the current shell ─────────────────────────────────────
# All NEXT_PUBLIC_* vars must be in the shell before Nx builds so they are
# baked into the Next.js client bundles at compile time.
set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

# ── Guard: reject placeholder or localhost values in required prod vars ────────
_validate_prod_env() {
  local errors=0

  _check_var() {
    local name="$1"
    local val="${!name:-}"

    if [ -z "$val" ]; then
      echo "  ERROR: ${name} is not set in ${ENV_FILE}"
      errors=$((errors + 1))
      return
    fi

    # Reject obvious placeholder patterns
    case "$val" in
      *replace-with* | *placeholder* | *REPLACE* | *<*>*)
        echo "  ERROR: ${name} still contains a placeholder value: ${val}"
        errors=$((errors + 1))
        ;;
    esac

    # Reject localhost / 127.0.0.1 in URL-type vars (DATABASE_URL is allowed
    # to use 127.0.0.1 since the DB container exposes on the loopback interface)
    case "$name" in
      NEXT_PUBLIC_API_URL | FRONTEND_URL | ALLOWED_ORIGINS | API_URL)
        case "$val" in
          *localhost* | *127.0.0.1*)
            echo "  ERROR: ${name} contains localhost — this will break production: ${val}"
            errors=$((errors + 1))
            ;;
        esac
        ;;
    esac
  }

  echo "==> Validating required env vars in ${ENV_FILE}..."
  _check_var JWT_SECRET
  _check_var DATABASE_URL
  _check_var NEXT_PUBLIC_API_URL
  _check_var ALLOWED_ORIGINS
  _check_var POSTGRES_USER
  _check_var POSTGRES_PASSWORD
  _check_var POSTGRES_DB

  if [ "$errors" -gt 0 ]; then
    echo ""
    echo "  Aborting: fix the ${errors} error(s) above in ${ENV_FILE} and re-run."
    exit 1
  fi

  echo "     All required env vars look good."
}

_validate_prod_env

cd "${REPO_ROOT}"

# ── 1. Pull latest code ───────────────────────────────────────────────────────
echo ""
echo "==> [1/8] Pulling latest code (branch: ${BRANCH})..."
git fetch origin "${BRANCH}"
git reset --hard "origin/${BRANCH}"

# ── 2. Install Node dependencies ──────────────────────────────────────────────
echo ""
echo "==> [2/8] Installing Node.js dependencies..."
npm ci --prefer-offline

# ── 3. Data layer ─────────────────────────────────────────────────────────────
echo ""
echo "==> [3/8] Starting Docker data layer (PostgreSQL + Redis)..."
docker compose -f docker-compose.prod.yml up -d --wait --remove-orphans
echo "     PostgreSQL  →  127.0.0.1:5432"
echo "     Redis       →  127.0.0.1:6379"

# ── Write a minimal .env so Prisma CLI picks up DATABASE_URL ─────────────────
# Prisma CLI always reads from .env in the project root (ignoring shell vars).
# We generate it from POSTGRES_* values already sourced from .env.prod.
# NOTE: This file is for Prisma CLI only. All other apps get their env vars
# from the shell environment (sourced above) and from the PM2 ecosystem config.
_DB_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5432/${POSTGRES_DB}?schema=public"
cat > "${REPO_ROOT}/.env" <<EOF
# Auto-generated by deploy.sh for Prisma CLI — do not edit manually.
DATABASE_URL="${_DB_URL}"
DIRECT_DATABASE_URL="${_DB_URL}"
EOF
echo "     .env  →  DATABASE_URL written for Prisma CLI (user: ${POSTGRES_USER}, db: ${POSTGRES_DB})"
unset _DB_URL

# ── 4. Database migrations ─────────────────────────────────────────────────────
echo ""
echo "==> [4/8] Running database migrations..."
npx prisma migrate deploy --schema=libs/shared/database/prisma/schema.prisma
npx prisma generate --schema=libs/shared/database/prisma/schema.prisma

# ── 5. Build all applications ─────────────────────────────────────────────────
echo ""
echo "==> [5/8] Building all applications..."
# NEXT_PUBLIC_* vars are now in the environment from step 0 and will be
# baked into the Next.js client bundles during this step.
echo "     Building api-backend..."
npx nx build api-backend --configuration=production

echo "     Building admin-panel..."
npx nx build admin-panel --configuration=production

echo "     Building vendor-dashboard..."
npx nx build vendor-dashboard --configuration=production

echo "     Building customer-portal..."
npx nx build customer-portal --configuration=production

# ── 6. Runtime directories ────────────────────────────────────────────────────
echo ""
echo "==> [6/8] Ensuring runtime directories exist..."
mkdir -p "${REPO_ROOT}/logs"
mkdir -p "${REPO_ROOT}/uploads"
mkdir -p "${REPO_ROOT}/uploads/whatsapp-session"

# ── 7. Sync nginx config ──────────────────────────────────────────────────────
echo ""
echo "==> [7/8] Syncing nginx config..."
NGINX_CONF="/etc/nginx/sites-available/water-supply-crm.conf"
NGINX_ENABLED="/etc/nginx/sites-enabled/water-supply-crm.conf"
CERTBOT_LIVE="/etc/letsencrypt/live"

# Verify that Let's Encrypt certs exist for all domains before deploying the
# HTTPS-enabled nginx config.  If any cert is missing, print setup instructions
# and abort so nginx doesn't fail to start with a missing cert reference.
_MISSING_CERTS=0
for domain in backend.testinglinq.com admin.testinglinq.com vendor.testinglinq.com portal.testinglinq.com; do
  if [ ! -f "${CERTBOT_LIVE}/${domain}/fullchain.pem" ]; then
    echo "  MISSING: SSL cert for ${domain}"
    _MISSING_CERTS=$((_MISSING_CERTS + 1))
  fi
done

if [ "${_MISSING_CERTS}" -gt 0 ]; then
  echo ""
  echo "  SSL certificates are missing for ${_MISSING_CERTS} domain(s)."
  echo "  Run this ONCE on the VPS, then re-run deploy.sh:"
  echo ""
  echo "    sudo certbot certonly --standalone \\"
  echo "      -d backend.testinglinq.com \\"
  echo "      -d admin.testinglinq.com \\"
  echo "      -d vendor.testinglinq.com \\"
  echo "      -d portal.testinglinq.com"
  echo ""
  echo "  Note: stop nginx first if it is running on port 80:"
  echo "    sudo systemctl stop nginx"
  echo "    # run certbot certonly above"
  echo "    sudo systemctl start nginx"
  exit 1
fi

sudo cp "${REPO_ROOT}/deploy/nginx/water-supply-crm.conf" "${NGINX_CONF}"
if [ ! -L "${NGINX_ENABLED}" ]; then
  sudo ln -s "${NGINX_CONF}" "${NGINX_ENABLED}"
fi

# Test config before reloading; if it fails, print the error and abort so the
# running nginx keeps serving the previous (working) config.
if ! sudo nginx -t; then
  echo ""
  echo "  ERROR: nginx config test failed — previous config is still active."
  echo "  Fix the error above and re-run deploy.sh."
  exit 1
fi

sudo nginx -s reload
echo "     nginx reloaded."

# ── 8. PM2 start / reload ─────────────────────────────────────────────────────
echo ""
echo "==> [8/8] Starting / reloading PM2 processes..."
pm2 startOrRestart "${REPO_ROOT}/ecosystem.config.js" --update-env
pm2 save

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  Deployment complete! (8/8 steps)                        ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
pm2 list
