import { Injectable } from '@nestjs/common';
// eslint-disable-next-line @typescript-eslint/no-require-imports
import PDFDocument = require('pdfkit');

const TYPE_COLOR: Record<string, string> = {
  PAYMENT: '#16a34a',
  DELIVERY: '#2563eb',
  ADJUSTMENT: '#d97706',
  COLLECTION: '#7c3aed',
  LOAD_OUT: '#0891b2',
  CHECK_IN: '#0891b2',
};

@Injectable()
export class CustomerStatementPdfService {
  async generate(data: {
    customer: any;
    transactions: any[];
    openingBalance: number;
    closingBalance: number;
    period: string;
  }): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      this.drawDocument(doc, data);
      doc.end();
    });
  }

  private drawDocument(doc: PDFKit.PDFDocument, data: any): void {
    const pageWidth = doc.page.width - 80;
    const { customer, transactions, openingBalance, closingBalance, period } = data;

    // ─── Header ────────────────────────────────────────────────────────────────
    doc.rect(40, 40, pageWidth, 70).fill('#0ea5e9');
    doc.fillColor('#ffffff').fontSize(18).font('Helvetica-Bold')
      .text('Water Supply CRM — Customer Statement', 55, 52);
    doc.fontSize(11).font('Helvetica')
      .text(`Period: ${period}`, 55, 76);
    doc.y = 125;

    // ─── Customer Info ──────────────────────────────────────────────────────────
    this.drawSectionTitle(doc, 'Customer Information');
    const infoY = doc.y + 4;
    doc.fontSize(10).font('Helvetica-Bold').fillColor('#374151');
    doc.text('Name:', 40, infoY);
    doc.text('Code:', 40, infoY + 18);
    doc.text('Address:', 40, infoY + 36);
    doc.text('Phone:', 40, infoY + 54);

    doc.font('Helvetica').fillColor('#1f2937');
    doc.text(customer.name ?? '—', 120, infoY);
    doc.text(customer.customerCode ?? '—', 120, infoY + 18);
    doc.text(customer.address ?? '—', 120, infoY + 36);
    doc.text(customer.phoneNumber ?? '—', 120, infoY + 54);
    doc.y = infoY + 76;

    // ─── Balance Summary ────────────────────────────────────────────────────────
    this.drawSectionTitle(doc, 'Balance Summary');
    const summaryY = doc.y + 4;
    const boxW = (pageWidth - 8) / 3;

    const activity = closingBalance - openingBalance;
    const boxes = [
      { label: 'Opening Balance', value: `Rs. ${openingBalance.toFixed(2)}`, color: '#dbeafe', textColor: '#1d4ed8' },
      { label: 'Period Activity', value: `Rs. ${activity >= 0 ? '+' : ''}${activity.toFixed(2)}`, color: '#fef9c3', textColor: '#a16207' },
      { label: 'Closing Balance', value: `Rs. ${closingBalance.toFixed(2)}`, color: '#dcfce7', textColor: '#15803d' },
    ];

    boxes.forEach((box, i) => {
      const x = 40 + i * (boxW + 4);
      doc.rect(x, summaryY, boxW, 52).fill(box.color);
      doc.fillColor(box.textColor).fontSize(9).font('Helvetica-Bold')
        .text(box.label, x + 6, summaryY + 8, { width: boxW - 12, align: 'center' });
      doc.fontSize(14).font('Helvetica-Bold')
        .text(box.value, x + 6, summaryY + 26, { width: boxW - 12, align: 'center' });
    });

    doc.y = summaryY + 60;

    // ─── Transaction Table ──────────────────────────────────────────────────────
    this.drawSectionTitle(doc, `Transactions (${transactions.length})`);
    this.drawTransactionTable(doc, transactions, openingBalance, pageWidth);

    // ─── Footer ─────────────────────────────────────────────────────────────────
    const pageBottom = doc.page.height - 40;
    doc.fontSize(8).fillColor('#9ca3af').font('Helvetica')
      .text(
        `Generated by Water Supply CRM • ${new Date().toLocaleString('en-PK')}`,
        40,
        pageBottom - 15,
        { width: pageWidth, align: 'center' },
      );
  }

  private drawSectionTitle(doc: PDFKit.PDFDocument, title: string): void {
    doc.rect(40, doc.y, doc.page.width - 80, 22).fill('#f1f5f9');
    doc.fillColor('#0f172a').fontSize(10).font('Helvetica-Bold')
      .text(title, 48, doc.y + 5);
    doc.moveDown(1.4);
  }

  private drawTransactionTable(
    doc: PDFKit.PDFDocument,
    transactions: any[],
    openingBalance: number,
    pageWidth: number,
  ): void {
    const cols = { date: 70, type: 70, description: 160, debit: 60, credit: 60, balance: 70 };

    const headerY = doc.y;
    doc.rect(40, headerY, pageWidth, 20).fill('#0f172a');
    doc.fillColor('#ffffff').fontSize(8).font('Helvetica-Bold');

    let x = 40;
    doc.text('Date', x + 2, headerY + 5, { width: cols.date }); x += cols.date;
    doc.text('Type', x + 2, headerY + 5, { width: cols.type }); x += cols.type;
    doc.text('Description', x + 2, headerY + 5, { width: cols.description }); x += cols.description;
    doc.text('Debit', x + 2, headerY + 5, { width: cols.debit, align: 'right' }); x += cols.debit;
    doc.text('Credit', x + 2, headerY + 5, { width: cols.credit, align: 'right' }); x += cols.credit;
    doc.text('Balance', x + 2, headerY + 5, { width: cols.balance, align: 'right' });

    doc.y = headerY + 22;

    if (!transactions.length) {
      doc.fillColor('#6b7280').fontSize(9).font('Helvetica')
        .text('No transactions in this period.', 40, doc.y + 8, { width: pageWidth, align: 'center' });
      return;
    }

    let runningBalance = openingBalance;

    transactions.forEach((tx, index) => {
      if (doc.y > doc.page.height - 100) {
        doc.addPage();
        doc.y = 50;
      }

      const rowY = doc.y;
      const rowBg = index % 2 === 0 ? '#ffffff' : '#f8fafc';
      doc.rect(40, rowY, pageWidth, 20).fill(rowBg);

      const amount = tx.amount ?? 0;
      // Positive amount = charge (debit), negative = payment (credit)
      const isDebit = amount > 0;
      const debit = isDebit ? amount : 0;
      const credit = !isDebit ? Math.abs(amount) : 0;
      runningBalance += amount;

      const typeColor = TYPE_COLOR[tx.type] ?? '#6b7280';

      doc.fillColor('#1f2937').fontSize(8).font('Helvetica');
      x = 40;
      doc.text(
        new Date(tx.createdAt).toLocaleDateString('en-PK', { day: '2-digit', month: 'short' }),
        x + 2, rowY + 5, { width: cols.date - 4 },
      ); x += cols.date;

      doc.fillColor(typeColor).font('Helvetica-Bold')
        .text(tx.type, x + 2, rowY + 5, { width: cols.type - 4 }); x += cols.type;

      doc.fillColor('#1f2937').font('Helvetica')
        .text(tx.description ?? tx.product?.name ?? '—', x + 2, rowY + 5, { width: cols.description - 4 }); x += cols.description;

      doc.text(debit > 0 ? `Rs.${debit.toFixed(2)}` : '', x + 2, rowY + 5, { width: cols.debit - 4, align: 'right' }); x += cols.debit;
      doc.fillColor('#16a34a')
        .text(credit > 0 ? `Rs.${credit.toFixed(2)}` : '', x + 2, rowY + 5, { width: cols.credit - 4, align: 'right' }); x += cols.credit;

      doc.fillColor('#1f2937')
        .text(`Rs.${runningBalance.toFixed(2)}`, x + 2, rowY + 5, { width: cols.balance - 4, align: 'right' });

      doc.y = rowY + 20;
    });
  }
}
