import { z } from 'zod';

export const customerSchema = z.object({
  // customerCode is omitted on create — auto-generated by backend
  // Only included on edit to display (read-only), not submitted
  name: z.string().min(2, 'Name must be at least 2 characters'),
  phoneNumber: z.string().min(10, 'Valid phone number required'),

  // Location
  address: z.string().min(5, 'Address must be at least 5 characters'),
  floor: z.string().optional(),
  nearbyLandmark: z.string().optional(),
  deliveryInstructions: z.string().optional(),
  googleMapsUrl: z.string().url('Enter a valid Google Maps URL').optional().or(z.literal('')),
  latitude: z.number().optional(),
  longitude: z.number().optional(),

  // Service
  routeId: z.string().uuid('Valid Route is required'),
  paymentType: z.enum(['MONTHLY', 'CASH']),

  // Delivery schedule — each active day maps to a van + optional sequence
  deliverySchedule: z.array(z.object({
    dayOfWeek: z.number().int().min(1).max(6),
    vanId: z.string().uuid('Van is required'),
    routeSequence: z.number().int().positive().optional(),
  })).min(1, 'Add at least one delivery day'),
});

export const customPriceSchema = z.object({
  productId: z.string().uuid('Product is required'),
  price: z.number().positive('Price must be positive'),
});

export type CustomerInput = z.infer<typeof customerSchema>;
export type CustomPriceInput = z.infer<typeof customPriceSchema>;
