import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '@water-supply-crm/database';
import {
  AdvanceInstallmentStatus,
  AdvancePlanStatus,
  PayrollPeriodStatus,
  Prisma,
  StaffLedgerCategory,
} from '@prisma/client';
import type { AuthUser } from '@water-supply-crm/types';
import { assertCanViewEmployeePayroll } from '../../common/helpers/payroll-view-scope.util';
import { PermissionService } from '../authz/permission.service';
import { StaffLedgerService } from './staff-ledger.service';
import { PAYROLL_ELIGIBLE_ROLES } from './payroll-entry.service';
import { computeRemainingBalance } from './advance-plan.util';
import { CreateAdvancePlanDto } from './dto/create-advance-plan.dto';
import { UpdateAdvancePlanDto } from './dto/update-advance-plan.dto';
import { CollectAdvanceInstallmentDto } from './dto/collect-advance-installment.dto';

/**
 * Advance Installments (owner-requested 2026-09-24,
 * docs/features/staff-payroll-financial-management.md §11's previously-unbuilt
 * "Installment-advance helper"). A `StaffAdvancePlan` is a real loan: the full
 * principal is disbursed once (an `ADVANCE_DISBURSEMENT` ledger entry, moves
 * cash), then recovered over however many periods it actually takes via
 * `StaffAdvanceInstallment` rows an admin actions each period — Collect (posts
 * an `ADVANCE_RECOVERY` entry, optionally a different amount than scheduled) or
 * Skip (no ledger entry, balance untouched — it simply rolls into the next
 * period's auto-generated installment, which is the entire mechanism behind a
 * 5-month plan silently becoming 6 if one month is skipped).
 *
 * The plain, one-off `ADVANCE` ledger category is untouched by this service —
 * it remains available (via the generic Log Ledger Entry dialog) for a
 * genuinely one-off advance with no repayment schedule.
 */
@Injectable()
export class StaffAdvancePlanService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly staffLedger: StaffLedgerService,
    private readonly permissions: PermissionService,
  ) {}

  /**
   * One transaction: post the full-principal `ADVANCE_DISBURSEMENT` (via
   * `StaffLedgerService.createTx`, same write path every other ledger entry
   * uses — the Cash Ledger period guard applies here too, same as a plain
   * ADVANCE) then create the plan linked to it. No installment rows yet —
   * those are auto-generated by `ensureInstallmentsForPeriod` the next time
   * `PayrollEntryService.generateDraft()` runs.
   */
  async create(user: AuthUser, dto: CreateAdvancePlanDto) {
    const employee = await this.prisma.user.findFirst({
      where: { id: dto.userId, vendorId: user.vendorId },
      select: { id: true, role: true, isActive: true },
    });
    if (!employee) throw new NotFoundException('Employee not found.');
    if (!PAYROLL_ELIGIBLE_ROLES.includes(employee.role)) {
      throw new BadRequestException(
        `Advance plans can only be created for payroll-eligible staff (${PAYROLL_ELIGIBLE_ROLES.join(', ')}).`,
      );
    }
    if (!employee.isActive) {
      throw new BadRequestException('Cannot create an advance plan for an inactive employee.');
    }

    return this.prisma.$transaction(async (tx) => {
      const disbursement = await this.staffLedger.createTx(tx, user, {
        userId: dto.userId,
        category: StaffLedgerCategory.ADVANCE_DISBURSEMENT,
        amount: -Math.abs(dto.principalAmount),
        effectiveDate: dto.disbursedAt,
        description: dto.note ?? `Advance disbursed — ₨${dto.principalAmount.toLocaleString()} installment plan`,
      });

      return tx.staffAdvancePlan.create({
        data: {
          vendorId: user.vendorId,
          userId: dto.userId,
          principalAmount: dto.principalAmount,
          defaultInstallmentAmount: dto.defaultInstallmentAmount,
          disbursedAt: new Date(dto.disbursedAt),
          disbursementLedgerEntryId: disbursement.id,
          note: dto.note ?? null,
          createdById: user.userId,
        },
      });
    });
  }

  /** Changes the standing default installment size / note going forward only. */
  async update(user: AuthUser, id: string, dto: UpdateAdvancePlanDto) {
    const plan = await this.prisma.staffAdvancePlan.findFirst({ where: { id, vendorId: user.vendorId } });
    if (!plan) throw new NotFoundException('Advance plan not found.');
    if (plan.status !== AdvancePlanStatus.ACTIVE) {
      throw new BadRequestException(`Only an ACTIVE plan can be updated (current status: ${plan.status}).`);
    }

    return this.prisma.staffAdvancePlan.update({
      where: { id },
      data: {
        ...(dto.defaultInstallmentAmount != null ? { defaultInstallmentAmount: dto.defaultInstallmentAmount } : {}),
        ...(dto.note !== undefined ? { note: dto.note } : {}),
      },
    });
  }

  /**
   * Collect a period's due installment. `dto.amount` overrides the
   * auto-generated `scheduledAmount` in either direction, capped at the
   * plan's live remaining balance (over-collecting is rejected, not silently
   * clamped — the admin should collect exactly the remainder instead).
   * Posts one `ADVANCE_RECOVERY` entry, dated today (when the cash/deduction
   * decision was actually made — not backdated to the period).
   */
  async collect(user: AuthUser, installmentId: string, dto: CollectAdvanceInstallmentDto) {
    return this.prisma.$transaction(async (tx) => {
      const installment = await tx.staffAdvanceInstallment.findFirst({
        where: { id: installmentId, vendorId: user.vendorId },
        include: { plan: true, period: true },
      });
      if (!installment) throw new NotFoundException('Advance installment not found.');
      this.assertPeriodActionable(installment.period.status);
      if (installment.status !== AdvanceInstallmentStatus.PENDING) {
        throw new BadRequestException(`Only a PENDING installment can be collected (current status: ${installment.status}).`);
      }

      const remaining = await computeRemainingBalance(tx, installment.planId, installment.plan.principalAmount);
      const amount = dto.amount ?? installment.scheduledAmount;
      if (amount > remaining) {
        throw new BadRequestException(
          `₨${amount.toLocaleString()} exceeds this plan's remaining balance of ₨${remaining.toLocaleString()}.`,
        );
      }

      const recovery = await this.staffLedger.createTx(tx, user, {
        userId: installment.plan.userId,
        category: StaffLedgerCategory.ADVANCE_RECOVERY,
        amount: -Math.abs(amount),
        effectiveDate: new Date().toISOString(),
        description: `Advance installment — ${installment.period.periodLabel}`,
      });

      const updated = await tx.staffAdvanceInstallment.update({
        where: { id: installmentId },
        data: {
          status: AdvanceInstallmentStatus.COLLECTED,
          actualAmount: amount,
          ledgerEntryId: recovery.id,
          decidedById: user.userId,
          decidedAt: new Date(),
        },
      });

      if (remaining - amount <= 0) {
        await tx.staffAdvancePlan.update({
          where: { id: installment.planId },
          data: { status: AdvancePlanStatus.COMPLETED },
        });
      }

      return updated;
    });
  }

  /**
   * No ledger entry — balance is untouched, so the next period's
   * `ensureInstallmentsForPeriod` naturally generates a fresh PENDING
   * installment against the still-open remaining balance.
   */
  async skip(user: AuthUser, installmentId: string) {
    return this.prisma.$transaction(async (tx) => {
      const installment = await tx.staffAdvanceInstallment.findFirst({
        where: { id: installmentId, vendorId: user.vendorId },
        include: { period: true },
      });
      if (!installment) throw new NotFoundException('Advance installment not found.');
      this.assertPeriodActionable(installment.period.status);
      if (installment.status !== AdvanceInstallmentStatus.PENDING) {
        throw new BadRequestException(`Only a PENDING installment can be skipped (current status: ${installment.status}).`);
      }

      return tx.staffAdvanceInstallment.update({
        where: { id: installmentId },
        data: {
          status: AdvanceInstallmentStatus.SKIPPED,
          actualAmount: 0,
          decidedById: user.userId,
          decidedAt: new Date(),
        },
      });
    });
  }

  private assertPeriodActionable(status: PayrollPeriodStatus) {
    if (status === PayrollPeriodStatus.LOCKED || status === PayrollPeriodStatus.PAID) {
      throw new BadRequestException('This installment belongs to a period that is already locked — it can no longer be actioned here.');
    }
  }

  /**
   * Every ACTIVE/COMPLETED plan for one employee, remaining balance computed
   * live, for the Employee Financial Profile page. Self-view or
   * `payroll:view_all`, same scoping as every other payroll read endpoint.
   */
  async listForEmployee(user: AuthUser, employeeUserId: string) {
    await assertCanViewEmployeePayroll(this.permissions, user, employeeUserId);

    const plans = await this.prisma.staffAdvancePlan.findMany({
      where: { vendorId: user.vendorId, userId: employeeUserId },
      orderBy: { disbursedAt: 'desc' },
    });

    return Promise.all(
      plans.map(async (plan) => ({
        ...plan,
        remainingBalance: await computeRemainingBalance(this.prisma as unknown as Prisma.TransactionClient, plan.id, plan.principalAmount),
      })),
    );
  }

  /**
   * ACTIVE plans for one employee scoped to a single period, each with this
   * period's installment (if one has been generated yet) — feeds
   * `PayrollEntryService.getBreakdown()`'s Advances section. Deliberately
   * takes raw ids (vendorId/userId/periodId), not `AuthUser` — the caller
   * (`getBreakdown`) has already done its own view-scope check on the entry.
   */
  async listForEmployeePeriod(vendorId: string, employeeUserId: string, periodId: string) {
    const plans = await this.prisma.staffAdvancePlan.findMany({
      where: { vendorId, userId: employeeUserId, status: AdvancePlanStatus.ACTIVE },
      orderBy: { disbursedAt: 'asc' },
    });

    return Promise.all(
      plans.map(async (plan) => {
        const remainingBalance = await computeRemainingBalance(
          this.prisma as unknown as Prisma.TransactionClient,
          plan.id,
          plan.principalAmount,
        );
        const installment = await this.prisma.staffAdvanceInstallment.findUnique({
          where: { planId_periodId: { planId: plan.id, periodId } },
        });
        return { ...plan, remainingBalance, installment };
      }),
    );
  }

  /**
   * Draft-generation hook — called from `PayrollEntryService.generateDraft()`
   * inside its own transaction, once per employee per period. For every ACTIVE
   * plan with remaining balance > 0 and no installment row yet for this
   * period, creates one PENDING placeholder sized to
   * `min(defaultInstallmentAmount, remainingBalance)`. Purely a "this plan is
   * due this period" marker — no ledger entry, no payable impact, until an
   * admin actually Collects or Skips it.
   */
  async ensureInstallmentsForPeriod(
    tx: Prisma.TransactionClient,
    vendorId: string,
    userId: string,
    periodId: string,
  ): Promise<void> {
    const plans = await tx.staffAdvancePlan.findMany({
      where: { vendorId, userId, status: AdvancePlanStatus.ACTIVE },
    });
    if (plans.length === 0) return;

    for (const plan of plans) {
      const existing = await tx.staffAdvanceInstallment.findUnique({
        where: { planId_periodId: { planId: plan.id, periodId } },
      });
      if (existing) continue;

      const remaining = await computeRemainingBalance(tx, plan.id, plan.principalAmount);
      if (remaining <= 0) continue; // defensive — should already be COMPLETED

      await tx.staffAdvanceInstallment.create({
        data: {
          vendorId,
          planId: plan.id,
          periodId,
          scheduledAmount: Math.min(plan.defaultInstallmentAmount, remaining),
          status: AdvanceInstallmentStatus.PENDING,
        },
      });
    }
  }

  /**
   * Lock-time finalization — called from `PayrollPeriodService.lockPeriod()`
   * inside its own transaction. Any installment still PENDING for this period
   * is system-decided as SKIPPED (same "finalize open decisions at lock time"
   * spirit as everything else that function does) — the balance rolls into
   * the next period exactly as an admin-initiated Skip would.
   */
  async autoSkipPendingForPeriod(tx: Prisma.TransactionClient, vendorId: string, periodId: string, actorId: string): Promise<void> {
    await tx.staffAdvanceInstallment.updateMany({
      where: { vendorId, periodId, status: AdvanceInstallmentStatus.PENDING },
      data: { status: AdvanceInstallmentStatus.SKIPPED, actualAmount: 0, decidedById: actorId, decidedAt: new Date() },
    });
  }
}
